language: node_js
node_js:
- '10.9'
dist: trusty
sudo: false

addons:

  ssh_known_hosts:
  - 45.33.75.6

before_install:
- openssl aes-256-cbc -K $encrypted_39f538b7df7f_key -iv $encrypted_39f538b7df7f_iv
  -in scripts/gatsby-deploy.enc -out scripts/gatsby-deploy -d

- eval "$(ssh-agent -s)"
- cp scripts/gatsby-deploy ~/.ssh/gatsby-deploy
- chmod 600 ~/.ssh/gatsby-deploy
- ssh-add ~/.ssh/gatsby-deploy
- echo -e "Host 45.33.75.6	\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
